version: '2'
services:
  web:
    container_name: absolute
    restart: always
    image: $CI_REGISTRY_IMAGE
    volumes:
      - ssl:/etc/nginx/ssl
      - uploads:/var/www/absolute/uploads
      - static:/var/www/absolute/static
    build:
      context: .
    command: uwsgi --ini uwsgi.ini
    expose:
      - "80"
    env_file:
      - absolute/.env
    environment:
      - VIRTUAL_HOST=$HOSTNAME,www.$HOSTNAME
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=$HOSTNAME,www.$HOSTNAME
      - LETSENCRYPT_EMAIL=$EMAIL
  redis:
    image: redis
    volumes:
      - redis-data:/data/
    container_name: absolute-redis
volumes:
  ssl:
  static:
  uploads:
  redis-data:

networks:
  default:
    external:
      name: nginx-proxy
