version: '2'
services:
  db:
    image: mdillon/postgis
  # rabbit:
  #   image: rabbitmq:alpine
  #   restart: always
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE
  # celery:
  #   build: .
  #   restart: always
  #   command: celery -A gett_airport worker -l info
  #   volumes_from:
  #     - web
  #   env_file:
  #     - gett_airport/.env
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    restart: always
    volumes:
      - .:/var/www/absolute
    ports:
      - 80:80
    env_file:
      - absolute/.env
    depends_on:
      - db
    stdin_open: true
    tty: true
  redis:
    image: redis
    volumes:
      - redis-data:/data/
    container_name: absolute-redis
volumes:
  # ssl:
  # static:
  redis-data: