# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('enter', 'enter'), ('exit', 'exit')], max_length=20)),
                ('datetimestamp', models.DateTimeField(auto_now_add=True)),
                ('photo', stdimage.models.StdImageField(null=True, upload_to=stdimage.utils.UploadToClassNameDirUUID(), verbose_name='image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
