# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171124_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, choices=[('enter', 'enter'), ('exit', 'exit')], max_length=20, null=True),
        ),
    ]
