# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171125_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
